name: "Clean API JSON Schema docs"

on:
  workflow_call:

permissions:
  contents: write

jobs:
  clean-apidoc:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: cleanup
        run: |
          REMOTE_BRANCH="apidoc-${{ github.event.ref }}"
          git push -f origin :${REMOTE_BRANCH}
